import type { Metadata } from "next";
import "./globals.css";

import { ToastProvider } from "../contexts/toastcontext";
import Navbar from "../components/navbar";
import { AuthProvider } from "../contexts/authcontext";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`bg-background text-white`}>


        <Suspense>
          <ToastProvider>
            <AuthProvider>
              <div className="min-h-screen flex flex-col">
                <main className="flex-1">
                  <Navbar />
                  {children}
                </main>
              </div>
            </AuthProvider>
          </ToastProvider>
        </Suspense>


      </body>
    </html>
  );
}
